#!/usr/bin/env bash
# Block all incoming traffic but 22, 443, 80

apt-get install uwf -y
ufw disable 
ufw enable

# Deny all incomin traficc
ufw default deny incoming
ufw default allow outgoing     
ufw allow 22/tcp 
ufw allow 443/tcp
ufw allow 80/tcp

