#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP header X-Served-By with the server hostname

# Install nginx if not already 
if ! command -v nginx &> /dev/unll; then 
	apt-get update -y 
	apt-get install -y nginx 
fi

# Start nginx 
systemctl start nginx 
systemctl enable nginx 

#Add custome header
echo "add_header X-Served-By \$hostname;" > /etc/nginx/conf.d/custom_header.conf 


# Reload and test nginx 
nginx -t 
systemctl reload nginx 
