#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# 1. Install HAProxy
apt-get -y update
apt-get -y install haproxy

# 2. Configure the init script to allow HAProxy to start
# (This handles the requirement: "Make sure that HAproxy can be managed via an init script")
if [ -f /etc/default/haproxy ]; then
    sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
fi

# 3. Add the configuration
# REPLACE 11.22.33.44 WITH YOUR REAL WEB-01 IP
# REPLACE 55.66.77.88 WITH YOUR REAL WEB-02 IP
cat <<EOT >> /etc/haproxy/haproxy.cfg

frontend www-http
    bind *:80
    reqadd X-Forwarded-Proto:\ http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server web-01 11.22.33.44:80 check
    server web-02 55.66.77.88:80 check
EOT

# 4. Restart HAProxy
service haproxy restart
