#!/usr/bin/env bash
# transfere a file from the client to the remote server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
IP=$2
USERNAME=$3
KEY=$4

scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP:~/"

