#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update -y && sudo apt-get install nginx -y 

#echo "Holberton School for the win!" > /var/www/html/index.html
sudo bash -c 'echo "<h1>Holberton School</h1>" > /var/www/html/school.html'

echo "Holberton School" > /var/www/html/index.html

sudo service nginx restart 
