#!/usr/bin/env bash 
# redirect me thingi 

sudo bash -c 'echo "<h1>Holberton School</h1>" > /var/www/html/index.html'

sudo sed -i '/server_name_;/a \ location/redirect_me {        \n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

sudo service nginx restart 





