#!/usr/bin/env bash 
# redirect me thingi 
# Hahahaha I am cooked

sudo apt-get update 
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

sudo bash -c 'echo "Holberton School" > /var/www/html/school.html'

sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
