#!/usr/bin/env bash 
# redirect me thingi 
# Hahahaha I am cooked


apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

# Add redirect only if it does not already exist
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sed -i "/server_name _;/a \\\
\\tlocation /redirect_me {\n\\t\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\\t}" /etc/nginx/sites-available/default
fi

service nginx restart

